name: VoidAfeLiagen
version: 1.0
main: com.example.voidafeliagen.AfeVoid
description: Bukkit plugin for generating and managing a void world.
author: Elias
commands:
  afevoid:
    description: Create or reset the void world
    usage: /afevoid
